"""create_push_management_tables

Revision ID: 1ef4b82f08de
Revises: 32e6d8f7f376
Create Date: 2025-05-21 15:46:24.467260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ef4b82f08de'
down_revision: Union[str, None] = '32e6d8f7f376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='推送来源ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='推送来源的易记名称'),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment="来源类型 (如 'dingtalk', 'wechat_mp', 'webhook', 'email')"),
    sa.Column('config', sa.JSON(), nullable=True, comment='来源的特定配置 (JSON格式)'),
    sa.Column('description', sa.Text(), nullable=True, comment='推送来源的描述 (可选)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='此推送来源是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_sources_id'), 'push_sources', ['id'], unique=False)
    op.create_index(op.f('ix_push_sources_name'), 'push_sources', ['name'], unique=True)
    op.create_index(op.f('ix_push_sources_source_type'), 'push_sources', ['source_type'], unique=False)
    op.create_table('push_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='消息ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='接收消息的用户ID (如果用户被删除，消息可保留)'),
    sa.Column('source_id', sa.Integer(), nullable=True, comment='消息的原始来源ID (如果来源被删除，消息可保留)'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='消息标题 (可选)'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息主体内容 (可以是纯文本、Markdown、HTML片段等)'),
    sa.Column('content_type', sa.String(length=50), nullable=False, comment="内容类型 (如 'text/plain', 'text/markdown', 'application/json')"),
    sa.Column('config', sa.JSON(), nullable=True, comment='来源的特定配置 (JSON格式)'),
    sa.Column('status', sa.String(length=50), nullable=False, comment="消息状态 (如 'unread', 'read', 'archived', 'failed_to_send')"),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False, comment='系统接收到消息的时间'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True, comment='消息实际发送给用户终端的时间 (可选)'),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='用户阅读消息的时间 (可选)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['source_id'], ['push_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_messages_id'), 'push_messages', ['id'], unique=False)
    op.create_index(op.f('ix_push_messages_received_at'), 'push_messages', ['received_at'], unique=False)
    op.create_index(op.f('ix_push_messages_source_id'), 'push_messages', ['source_id'], unique=False)
    op.create_index(op.f('ix_push_messages_status'), 'push_messages', ['status'], unique=False)
    op.create_index(op.f('ix_push_messages_user_id'), 'push_messages', ['user_id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='订阅关系ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='订阅用户ID'),
    sa.Column('source_id', sa.Integer(), nullable=False, comment='订阅的推送来源ID'),
    sa.Column('config', sa.JSON(), nullable=True, comment='来源的特定配置 (JSON格式)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='用户是否希望接收此订阅的推送'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='订阅创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='订阅最后更新时间'),
    sa.ForeignKeyConstraint(['source_id'], ['push_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_id', name='uq_user_source_subscription')
    )
    op.create_index(op.f('ix_push_subscriptions_id'), 'push_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_source_id'), 'push_subscriptions', ['source_id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.add_column('navigation_groups', sa.Column('description', sa.Text(), nullable=True, comment='导航分组描述 (可选)'))
    op.add_column('navigation_groups', sa.Column('order_index', sa.Integer(), nullable=False, comment='用于用户自定义排序的索引'))
    op.alter_column('navigation_groups', 'id',
               existing_type=sa.INTEGER(),
               comment='导航分组ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('navigation_groups_id_seq'::regclass)"))
    op.alter_column('navigation_groups', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='导航分组名称',
               existing_nullable=False)
    op.alter_column('navigation_groups', 'user_id',
               existing_type=sa.INTEGER(),
               comment='所属用户ID',
               existing_nullable=False)
    op.alter_column('navigation_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment='创建时间')
    op.alter_column('navigation_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment='最后更新时间')
    op.create_index(op.f('ix_navigation_groups_name'), 'navigation_groups', ['name'], unique=False)
    op.drop_constraint('navigation_groups_user_id_fkey', 'navigation_groups', type_='foreignkey')
    op.create_foreign_key(None, 'navigation_groups', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('navigation_groups', 'order')
    op.add_column('navigation_items', sa.Column('order_index', sa.Integer(), nullable=False, comment='组内排序索引'))
    op.alter_column('navigation_items', 'id',
               existing_type=sa.INTEGER(),
               comment='导航项ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('navigation_items', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='导航项标题',
               existing_nullable=False)
    op.alter_column('navigation_items', 'url',
               existing_type=sa.VARCHAR(length=2083),
               comment='导航项链接 URL (URL RFC 推荐最大长度)',
               existing_nullable=False)
    op.alter_column('navigation_items', 'icon_url',
               existing_type=sa.VARCHAR(length=2083),
               comment='导航项图标的 URL (可选)',
               existing_nullable=True)
    op.alter_column('navigation_items', 'description',
               existing_type=sa.TEXT(),
               comment='导航项描述 (可选)',
               existing_nullable=True)
    op.alter_column('navigation_items', 'group_id',
               existing_type=sa.INTEGER(),
               comment='所属导航分组ID',
               existing_nullable=False)
    op.alter_column('navigation_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment='创建时间')
    op.alter_column('navigation_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment='最后更新时间')
    op.drop_constraint('navigation_items_group_id_fkey', 'navigation_items', type_='foreignkey')
    op.create_foreign_key(None, 'navigation_items', 'navigation_groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_column('navigation_items', 'order')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               comment='用户名，唯一',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='电子邮箱，唯一，可选',
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='哈希后的密码',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='账户是否激活')
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='是否为超级管理员')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment='创建时间 (带时区)')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment='最后更新时间 (带时区)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='最后更新时间 (带时区)')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='创建时间 (带时区)')
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='是否为超级管理员')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='账户是否激活')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='哈希后的密码',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='电子邮箱，唯一，可选',
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='用户名，唯一',
               existing_nullable=False)
    op.add_column('navigation_items', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'navigation_items', type_='foreignkey')
    op.create_foreign_key('navigation_items_group_id_fkey', 'navigation_items', 'navigation_groups', ['group_id'], ['id'])
    op.alter_column('navigation_items', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='最后更新时间')
    op.alter_column('navigation_items', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='创建时间')
    op.alter_column('navigation_items', 'group_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属导航分组ID',
               existing_nullable=False)
    op.alter_column('navigation_items', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='导航项描述 (可选)',
               existing_nullable=True)
    op.alter_column('navigation_items', 'icon_url',
               existing_type=sa.VARCHAR(length=2083),
               comment=None,
               existing_comment='导航项图标的 URL (可选)',
               existing_nullable=True)
    op.alter_column('navigation_items', 'url',
               existing_type=sa.VARCHAR(length=2083),
               comment=None,
               existing_comment='导航项链接 URL (URL RFC 推荐最大长度)',
               existing_nullable=False)
    op.alter_column('navigation_items', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='导航项标题',
               existing_nullable=False)
    op.alter_column('navigation_items', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='导航项ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('navigation_items', 'order_index')
    op.add_column('navigation_groups', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'navigation_groups', type_='foreignkey')
    op.create_foreign_key('navigation_groups_user_id_fkey', 'navigation_groups', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_navigation_groups_name'), table_name='navigation_groups')
    op.alter_column('navigation_groups', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='最后更新时间')
    op.alter_column('navigation_groups', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='创建时间')
    op.alter_column('navigation_groups', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属用户ID',
               existing_nullable=False)
    op.alter_column('navigation_groups', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='导航分组名称',
               existing_nullable=False)
    op.alter_column('navigation_groups', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='导航分组ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('navigation_groups_id_seq'::regclass)"))
    op.drop_column('navigation_groups', 'order_index')
    op.drop_column('navigation_groups', 'description')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_source_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_push_messages_user_id'), table_name='push_messages')
    op.drop_index(op.f('ix_push_messages_status'), table_name='push_messages')
    op.drop_index(op.f('ix_push_messages_source_id'), table_name='push_messages')
    op.drop_index(op.f('ix_push_messages_received_at'), table_name='push_messages')
    op.drop_index(op.f('ix_push_messages_id'), table_name='push_messages')
    op.drop_table('push_messages')
    op.drop_index(op.f('ix_push_sources_source_type'), table_name='push_sources')
    op.drop_index(op.f('ix_push_sources_name'), table_name='push_sources')
    op.drop_index(op.f('ix_push_sources_id'), table_name='push_sources')
    op.drop_table('push_sources')
    # ### end Alembic commands ###
