"""aumg update1

Revision ID: 5cbd1029d77a
Revises: 1ef4b82f08de
Create Date: 2025-05-21 20:56:51.767889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cbd1029d77a'
down_revision: Union[str, None] = '1ef4b82f08de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('navigation_items', 'url',
               existing_type=sa.VARCHAR(length=2083),
               comment='导航项链接 URL',
               existing_comment='导航项链接 URL (URL RFC 推荐最大长度)',
               existing_nullable=False)
    op.add_column('push_messages', sa.Column('raw_data', sa.JSON(), nullable=True, comment='从来源接收到的原始数据 (JSON格式)'))
    op.drop_column('push_messages', 'config')
    op.add_column('push_subscriptions', sa.Column('user_specific_config', sa.JSON(), nullable=True, comment='用户针对此订阅的特定配置 (JSON格式)'))
    op.drop_column('push_subscriptions', 'config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_subscriptions', sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='来源的特定配置 (JSON格式)'))
    op.drop_column('push_subscriptions', 'user_specific_config')
    op.add_column('push_messages', sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='来源的特定配置 (JSON格式)'))
    op.drop_column('push_messages', 'raw_data')
    op.alter_column('navigation_items', 'url',
               existing_type=sa.VARCHAR(length=2083),
               comment='导航项链接 URL (URL RFC 推荐最大长度)',
               existing_comment='导航项链接 URL',
               existing_nullable=False)
    # ### end Alembic commands ###
